# Generated by Django 4.1 on 2022-09-12 11:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_petani'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sumber_Pendanaan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_donor', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='petani',
            name='desa',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='petani',
            name='gelar_belakang',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='petani',
            name='gelar_depan',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='petani',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='petani',
            name='kabupaten',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='petani',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='petani',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='petani',
            name='nik',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_kegiatan', models.CharField(max_length=100)),
                ('tahun_kegiatan', models.DateField()),
                ('tanggal_kegiatan', models.DateField()),
                ('sumber_pendanaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sumber_pendanaan')),
            ],
        ),
    ]
