# Generated by Django 4.1 on 2022-09-12 12:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_kegiatan_options_alter_petani_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kegiatan_Petani',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kegiatan')),
                ('id_petani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.petani')),
            ],
            options={
                'verbose_name': 'Kegiatan Petani',
                'verbose_name_plural': 'Kegiatan Petani',
            },
        ),
    ]
