# Generated by Django 4.1 on 2022-09-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_tanggal_kegiatan_kegiatan_tanggal_mulai_kegiatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan',
            name='tanggal_selesai_kegiatan',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
