# Generated by Django 4.1 on 2022-09-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_kpi_alter_kegiatan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='nama_kpi',
            field=models.CharField(max_length=100),
        ),
    ]
