# Generated by Django 4.1 on 2022-09-13 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_kegiatan_tanggal_selesai_kegiatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan',
            name='tanggal_selesai_kegiatan',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
    ]
