# Generated by Django 4.1 on 2022-09-15 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_kpi_alter_kegiatan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpi',
            options={'ordering': ('nama_kpi',), 'verbose_name': 'Key Performance Indicator'},
        ),
        migrations.RenameField(
            model_name='kpi',
            old_name='nama_KPI',
            new_name='nama_kpi',
        ),
        migrations.RenameField(
            model_name='kpi',
            old_name='tahun_KPI',
            new_name='tahun_kpi',
        ),
        migrations.AlterField(
            model_name='kpi',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
