# Generated by Django 4.1 on 2022-09-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_kpi_nama_kpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kegiatan',
            name='kpi',
        ),
        migrations.DeleteModel(
            name='KPI',
        ),
    ]
