# Generated by Django 4.1 on 2022-09-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='kpi',
            field=models.ManyToManyField(to='api.kpi'),
        ),
    ]
