# Generated by Django 4.1 on 2022-09-28 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_kegiatan_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
