# Generated by Django 4.1 on 2022-09-28 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_article_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1900)]),
        ),
    ]
