# Generated by Django 4.1 on 2022-08-25 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='group',
        ),
    ]
