# Generated by Django 4.1 on 2022-08-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_remove_catalog_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='catalog',
            name='tags',
            field=models.ManyToManyField(to='operation.tag'),
        ),
    ]
