# Generated by Django 4.1 on 2022-09-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_alter_tag_options_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='category',
            field=models.CharField(choices=[('JSON', 'json'), ('XML', 'xml'), ('WFS', 'wfs'), ('WMS', 'wms'), ('WMTS', 'wmts')], default='JSON', max_length=50),
        ),
    ]
